language: node_js
node_js: lts/*

branches:
  only:
    - master

cache:
  directories:
    - node_modules
 
before_install:
  - export TZ='America/New_York'

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo generate
  - cp README.md ./public/

after_script:
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i "s/github_repo_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy