language: node_js
node_js: lts/*

branches:
  only:
    - master

cache:
  directories:
    - node_modules
 
before_install:
  - export TZ='America/New_York'

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo generate
  - cp README.md ./public/